Environment Variable Support for UpdateKey Program
terra-project/oracle-feeder pull request #10
Opened 2020-11-07 01:20 UTC by ljk662

This PR adds the ability to use environment variables instead of user input for the secret arguments in the Update Key program.

2020-12-19 14:54 UTC, hanjukim requested changes

2020-12-19 14:54 UTC, hanjukim commented on feeder/src/updateKey.ts
> +  if (password == '') {
could you change == to === ?

2020-12-19 14:54 UTC, hanjukim commented on feeder/src/updateKey.ts
> +  if (mnemonic == '') {
This too.

2020-12-19 15:39 UTC, ljk662 commented on feeder/src/updateKey.ts
> +  if (password == '') {
done

2020-12-19 15:39 UTC, ljk662 commented on feeder/src/updateKey.ts
> +  if (mnemonic == '') {
done

2020-12-21 11:04 UTC, hanjukim approved these changes

2020-12-21 11:05 UTC, hanjukim commented
Thank you!

2020-12-21 11:05 UTC, merged